### ISSUE TITLE
Exception when invoking CarsCatalogController.GetAllCarsAsync in asp-net-core-microservices-with-azure-and-docker

### ISSUE THREAD

**Issue by mgmccarthy** [Daniel-Krzyczkowski/MicrosoftAzure#12]
I realize that this solution is meant to be run in Docker, however, I can run the CarsIsland.Catalog.API by picking the name of the project and hitting F5
![image](https://user-images.githubusercontent.com/2428993/100911863-9e3c2000-3484-11eb-8d24-b4196dd88bbb.png)
![image](https://user-images.githubusercontent.com/2428993/100912517-6bdef280-3485-11eb-96b2-b674bd99d392.png)

I have created a new Service Bus Namespace
![image](https://user-images.githubusercontent.com/2428993/100912039-d6dbf980-3484-11eb-9957-722ee5d01f57.png)

and have plugged the Service Bus connection string into the appsettings.Development.json files of CarsIsland.Catalog.API and CarsIsland.Reservation.API projects

I've even create the service bus topic by hand in the azure portal like in the readme file:
![image](https://user-images.githubusercontent.com/2428993/100912304-228ea300-3485-11eb-8476-8f01777e7aed.png)

However, and exception is thrown when I try to invoke CarsCatalogController.GetAllCarsAsync in Postman
![image](https://user-images.githubusercontent.com/2428993/100912710-b19bbb00-3485-11eb-841d-0710f18f8899.png)

The exception is a System.ArgumentException and it's thrown from ServiceBusConnectionManagementService
![image](https://user-images.githubusercontent.com/2428993/100912870-e14ac300-3485-11eb-987b-290ae91edbc5.png)

Here's the full stack trace:
```
System.ArgumentException
  HResult=0x80070057
  Message=The argument  is null or white space.
  Source=Microsoft.Azure.ServiceBus
  StackTrace:
   at Microsoft.Azure.ServiceBus.TopicClient..ctor(ServiceBusConnection serviceBusConnection, String entityPath, RetryPolicy retryPolicy)
   at Microsoft.Azure.ServiceBus.TopicClient..ctor(String connectionString, String entityPath, RetryPolicy retryPolicy)
   at Microsoft.Azure.ServiceBus.TopicClient..ctor(ServiceBusConnectionStringBuilder connectionStringBuilder, RetryPolicy retryPolicy)
   at CarsIsland.EventBus.Services.ServiceBusConnectionManagementService..ctor(ILogger`1 logger, ServiceBusConnectionStringBuilder serviceBusConnectionStringBuilder) in C:\Projects\MicrosoftAzure\asp-net-core-microservices-with-azure-and-docker\src\CarsIsland\BuildingBlocks\CarsIsland.EventBus\Services\ServiceBusConnectionManagementService.cs:line 20
   at CarsIsland.Catalog.API.Core.DependencyInjection.IntegrationServiceCollectionExtensions.<>c__DisplayClass0_0.<AddIntegrationServices>b__0(IServiceProvider sp) in C:\Projects\MicrosoftAzure\asp-net-core-microservices-with-azure-and-docker\src\CarsIsland\Catalog\CarsIsland.Catalog.API\Core\DependencyInjection\IntegrationServiceCollectionExtensions.cs:line 32
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CarsIsland.Catalog.API.Core.DependencyInjection.IntegrationServiceCollectionExtensions.<>c__DisplayClass0_0.<AddIntegrationServices>b__1(IServiceProvider sp) in C:\Projects\MicrosoftAzure\asp-net-core-microservices-with-azure-and-docker\src\CarsIsland\Catalog\CarsIsland.Catalog.API\Core\DependencyInjection\IntegrationServiceCollectionExtensions.cs:line 37
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

I can't help but think I'm missing some type of config that might have been in your user secrets or there are other service bus namespace artifacts I have to set up (subscriptions/rules for the topic, queues???)

Thanks!

**Comment by Daniel-Krzyczkowski** [comment]
Hi Michael,

I went through the code and verified it. Unfortunately I cannot reproduce it but I can provide you more details about the steps how subscription is configured in the Azure Service Bus in the Azure portal.

1. I created Azure Service Bus namespace:
![sb1](https://user-images.githubusercontent.com/15244422/100980541-a9a35000-3545-11eb-9ad1-852cf7003423.PNG)

2. Then I created new topic - "cars-island-events":
![sb2](https://user-images.githubusercontent.com/15244422/100980580-bde74d00-3545-11eb-8f58-2afba51e7f0f.PNG)

![sb3](https://user-images.githubusercontent.com/15244422/100980659-deafa280-3545-11eb-9d2a-03ede7030e0a.PNG)

3. Then I created new subscription to the "cars-island-events" topic called "catalog":

![sb4](https://user-images.githubusercontent.com/15244422/100980765-0a328d00-3546-11eb-812f-2a0e434337c7.PNG)

![sb5](https://user-images.githubusercontent.com/15244422/100980772-0bfc5080-3546-11eb-9288-2d8faf9c6a2b.PNG)

4. In the last step I created new shared access policy with listen and send permissions and I copied primary connection string value for it:

![sb6](https://user-images.githubusercontent.com/15244422/100980892-3d751c00-3546-11eb-8b1f-fa57f866bf13.PNG)

![sb7](https://user-images.githubusercontent.com/15244422/100980970-63022580-3546-11eb-89a9-4ed2d80ee298.PNG)

5. Then in the "appsettings.Development.json" file I put this connection string in the AzureServiceBusSettings:SubscriptionClientName section:

  "AzureServiceBusSettings": {
    "ConnectionString": "------> connection string copied above",
    "SubscriptionClientName": "catalog"
  }

6. Then Topic Client was successfully created:

![sb8](https://user-images.githubusercontent.com/15244422/100981316-f2a7d400-3546-11eb-997a-eb19d2c920b0.png)

Please let me know if it helped.

**Comment by mgmccarthy** [comment]
@Daniel-Krzyczkowski, this worked. Thanks so much!

**Comment by mgmccarthy** [comment]
@Daniel-Krzyczkowski, this worked. Thanks so much!

**Comment by Daniel-Krzyczkowski** [comment]
Great! Good luck!
